### GENERAL SETTINGS ###

# Site settings
title: <%= projectName %>
keywords: <%= projectKeywords %>
description: <%= projectDescription %>
baseurl: <%= githubRepoName %>
### Build settings
markdown: kramdown
highlighter: pygments

### Social
# Provide full url for linkedin and youtube
social: 
 - 
  facebook: <%= socialFacebook %>
  twitter: <%= socialTwitter %>
  linkedin: <%= socialLinkedin %>
  youtube: <%= socialYoutube %>
  github: <%= socialGithub %>

email: <%= email %>
